# Generated by Django 5.1.6 on 2025-04-20 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feestructure',
            old_name='fee_types',
            new_name='fee_type',
        ),
    ]
