# Generated by Django 5.1.6 on 2025-04-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rename_fee_types_feestructure_fee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
